### ISSUE TITLE
Issue install cockroach with no error output

### ISSUE THREAD

**Issue by Scalahansolo** [cockroachdb/homebrew-tap#112]
When trying to install cockroach DB on a recently setup M1 macbook I get the follow error.

```
2022-10-11 21:20:56 +0000

/opt/homebrew/Cellar/cockroach/22.1.8/bin/cockroach
gen
man
--path=/opt/homebrew/Cellar/cockroach/22.1.8/share/man/man1


HOMEBREW_VERSION: 3.6.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb52a12144e80118c112ea744ab65ab6ca997d67
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d9469643c55a5089adafafe04d19881840ae78f4
Core tap last commit: 15 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j10
CMAKE_PREFIX_PATH: /opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/12
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin
```

When running `brew install cockroach` I get the follow error, and it seems like the binary isn't actually being installed at that location

**Comment by mintgolddust** [comment]
2022-12-22 14:45:14 +0000

install_name_tool
-id
/usr/local/Cellar/cockroach/22.2.0/lib/cockroach/libgeos.dylib
/usr/local/Cellar/cockroach/22.2.0/lib/cockroach/libgeos.dylib

rosetta error: /var/db/oah/f1d6bb9509473aa97027eaba1db72ebe945d9c3240abab4614d4ce708bd0a64b/084c5fde019781190098ff616399f1140d421c851d6668fd2ca78d869e57d592/install_name_tool.aot: attachment of code signature supplement failed: 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Issue install cockroach with no error output https://github.com/cockroachdb/homebrew-tap/issues/112

**Comment by rail** [comment]
I believe this should be fixed by https://github.com/cockroachdb/homebrew-tap/pull/123 and https://github.com/cockroachdb/homebrew-tap/pull/134

Fell free to reopen if it happens again.
