### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/homebrew-tap#27]
This tap is used with either `brew install cockroachdb/cockroach/cockroach` or `brew tap cockroachdb/cockroach; brew install cockroach`. That's a lot of repetitions of the word `cockroach`. MongoDB (among others) does something that's arguably nicer-looking, replacing the second component (the most flexible part of the naming scheme) with `brew`, resulting in `mongodb/brew/mongodb-community`. This looks a little nicer for the user, although it does mean that they have a mostly-invisible repo with the silly name [`homebrew-brew`](https://github.com/mongodb/homebrew-brew). Other projects use `tap` for this. 

We'll be reactivating this tap for the 19.2 launch; after that it gets harder to change. So if we decide we want to rename the repo, now's our best chance.

**Comment by kenliu** [comment]
I like the idea of renaming for clarity and consistency with other projects (less surprise for the user), but a little unclear what you are specifically recommending here.

**Comment by bdarnell** [comment]
For non-core packages, `brew` uses a 3-part naming scheme: `$ORG/$REPO/$PACKAGE`. `$ORG` is a github organization, so that's definitely `cockroachdb` for us. `$PACKAGE` is how it's referred to in most commands, so it also needs to be `cockroach` (or `cockroachdb`). These are used to construct urls like `github.com/$ORG/homebrew-$REPO/Formula/$PACKAGE.rb`. 

So the options are:
1. As-is: `brew install cockroachdb/cockroach/cockroach` or `brew tap cockroachdb/cockroach && brew install cockroach`
2. Rename this repo from `homebrew-cockroach` to `homebrew-brew`: `brew install cockroachdb/brew/cockroach` or `brew tap cockroachdb/brew && brew install cockroach`
3. Rename to `homebrew-tap`: `brew install cockroachdb/tap/cockroach` or `brew tap cockroachdb/tap && brew install cockroach`

The two most common non-core packages according to [brew's analytics](https://formulae.brew.sh/analytics/install-on-request/30d/) are heroku and mongo, both of which use `/brew/`. After those two, `/brew/` is less common and we see either repetitive names or `/tap/`. 

My preference is option 2.

**Comment by kenliu** [comment]
IMO it's a toss-up between #2 and #3 but I think #3 communicates more clearly that we are a non-core package.

**Comment by bdarnell** [comment]
OK, renaming to `cockroach-tap`.
