### ISSUE TITLE
allow older versions to be installed (<= v22.1)

### ISSUE THREAD

**Issue by otan** [cockroachdb/homebrew-tap#42]
I've seen some other brews have older versions (e.g. you can do `brew install go@1.13`), we should probably have support for older versions of CRDB with something like `brew install cockroachdb/tap/cockroach@19.2` and the like.

**Edit 2023-07-12**: we will support this from v22.2+ onwards. we can work on v22.1 and back if we change the template files to not include the ARM builds.

**Comment by Scalahansolo** [comment]
How is this really 3 years old? For a company the size of Cockroach, this feels like table stakes.

**Comment by otan** [comment]
seems an issue lost to time i've bumped up the priority internally (i am personally no longer involved with releases), but here are some things that hopefully temporarily unblocks you:
* you can download the binary and run it manually: https://www.cockroachlabs.com/docs/stable/install-cockroachdb-mac.html#install-binary
* if you want to use brew, you can pull, i've made a PR #158 which you can install manually by pulling the branch and running `brew install ./Formula/cockroach@22.2.rb`

**Comment by otan** [comment]
change has been merged for 22.2. updated issue to reflect older versions.

**Comment by rail** [comment]
Shall we resolve this as done, because ATM we support 23.1 and 22.2 only. 22.1 is not [maintained](https://www.cockroachlabs.com/docs/releases/release-support-policy.html#current-supported-releases) anymore.

**Comment by Scalahansolo** [comment]
I think it's fair to say this is resolve. However, this is something I think should be maintained going forward. Since 22.2 is where the arm support came in to the tap, 22+ seems reasonable. In theory every new release of cockroach going forward should have the ability to do this. 

Just because something may not be maintained anymore doesn't mean people wouldn't still be using it (disregard whether they *should* be)

**Comment by rail** [comment]
The current release process should keep the versions up to date for every supported release. Let's call it done. \o/
